import type { NextPage } from "next";
import Head from "next/head";
import { useCallback, useMemo } from "react";
import {
  Editable,
  withReact,
  Slate,
  RenderElementProps,
  RenderLeafProps,
} from "slate-react";
import isHotkey from "is-hotkey";
import { createEditor } from "slate";
import { withHistory } from "slate-history";
import { BlockButton, Element, Leaf, MarkButton } from "../ui";
import { HOTKEYS } from "../constants";
import { toggleMark } from "../utlis";
import {
  FormatBold,
  FormatItalic,
  FormatUnderlined,
  Code,
  LooksOne,
  LooksTwo,
  FormatListNumbered,
  Looks3,
} from "@emotion-icons/material";
import {
  FormatAlignCenter,
  FormatAlignJustify,
  FormatAlignLeft,
  FormatAlignRight,
  FormatListBulleted,
  Superscript,
} from "emotion-icons/material";
import { Container, Heading, Text, VStack, Wrap } from "@chakra-ui/react";
import { CodeSquare } from "emotion-icons/bootstrap";

type DynamicType = {
  [key: string]: string;
};

const Home: NextPage = () => {
  const renderElement = useCallback(
    (props: RenderElementProps) => <Element {...props} />,
    []
  );
  const renderLeaf = useCallback(
    (props: RenderLeafProps) => <Leaf {...props} />,
    []
  );
  const editor = useMemo(() => withHistory(withReact(createEditor())), []);

  const initialValue: any[] = [
    {
      type: "paragraph",
      children: [{ text: "Welcome to this simple text editor", bold: true }],
    },
  ];

  return (
    <div>
      <Head>
        <title>SlateJS Exploration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxW="4xl">
          <VStack py={10} textAlign="center">
            <Heading>Joshua - SlateJS Exploration</Heading>
            <Text>A rich text editor based on SlateJS</Text>
          </VStack>
          <Slate editor={editor} value={initialValue}>
            <Wrap
              borderBottom="2px solid"
              borderColor="#CCCCCC"
              paddingBottom={4}
              marginBottom={4}
              marginTop={4}
            >
              <MarkButton format="bold" icon={<FormatBold size={25} />} />
              <MarkButton format="italic" icon={<FormatItalic size={25} />} />
              <MarkButton
                format="underline"
                icon={<FormatUnderlined size={25} />}
              />
              <MarkButton format="code" icon={<Code size={25} />} />
              <MarkButton format="sup" icon={<Superscript size={25} />} />
              <BlockButton
                format="code-block"
                icon={<CodeSquare size={25} />}
              />
              <BlockButton format="heading-one" icon={<LooksOne size={25} />} />
              <BlockButton format="heading-two" icon={<LooksTwo size={25} />} />
              <BlockButton format="heading-three" icon={<Looks3 size={25} />} />
              <BlockButton
                format="numbered-list"
                icon={<FormatListNumbered size={25} />}
              />
              <BlockButton
                format="bulleted-list"
                icon={<FormatListBulleted size={25} />}
              />
              <BlockButton format="left" icon={<FormatAlignLeft size={25} />} />
              <BlockButton
                format="center"
                icon={<FormatAlignCenter size={25} />}
              />
              <BlockButton
                format="right"
                icon={<FormatAlignRight size={25} />}
              />
              <BlockButton
                format="justify"
                icon={<FormatAlignJustify size={25} />}
              />
            </Wrap>
            <Editable
              renderElement={renderElement}
              renderLeaf={renderLeaf}
              placeholder="Enter some rich text…"
              spellCheck
              autoFocus
              onKeyDown={(event) => {
                for (const hotkey in HOTKEYS) {
                  if (isHotkey(hotkey, event)) {
                    event.preventDefault();
                    const mark = (HOTKEYS as DynamicType)[hotkey];
                    toggleMark(editor, mark);
                  }
                }
              }}
            />
          </Slate>
        </Container>
      </main>
    </div>
  );
};

export default Home;
